<?php

namespace App\Metadata\CAS;

use App\Metadata\AudMD;

class CasCPMD
{
    public const LOGICAL_EXCLUSION = false;
    public const FIELDS_PK = [];
    public const FIELDS_FK = array();
    public const TABLE_IDX = array();
    public const FIELDS_REQUIRED = [
        'CasAppKey',
        'CasAppToken',
        'CasAppName',
        'CasAppEnv',
        'CasAppUrl',
        'CasAppAdmFirstName',
        'CasAppAdmLastName',
        'CasAppAdmAccount',
        'CasAppAdmPassword',
        'CasAppAdmProfile',
        'CasAppSupFirstName',
        'CasAppSupLastName',
        'CasAppSupAccount',
        'CasAppSupPassword',
        'CasAppSupProfile',
    ];
    public const FIELDS_AUDIT = [];
    public const FIELDS = [
        'CasAppKey',
        'CasAppToken',
        'CasAppName',
        'CasAppEnv',
        'CasAppUrl',
        'CasAppAdmFirstName',
        'CasAppAdmLastName',
        'CasAppAdmAccount',
        'CasAppAdmPassword',
        'CasAppAdmProfile',
        'CasAppSupFirstName',
        'CasAppSupLastName',
        'CasAppSupAccount',
        'CasAppSupPassword',
        'CasAppSupProfile',
    ];
    public const FIELDS_MD = [
        'CasAppKey' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Chave da aplicação',
            'ShortLabel' => 'Chave do App',
            'TextPlaceholder' => '',
            'TextHelp' => 'Deve ser uma string aleatória de 36 caracteres.',
        ],
        'CasAppToken' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Token da aplicação',
            'ShortLabel' => 'Token do App',
            'TextPlaceholder' => '',
            'TextHelp' => 'Deve ser uma string aleatória de 36 caracteres.',
        ],
        'CasAppName' => [
            'Type' => 'string',
            'Length' => 20,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Nome da sua aplicação',
            'ShortLabel' => 'Nome do App',
            'TextPlaceholder' => 'MANAGER',
            'TextHelp' => 'Breve nome apresentado no topo do site.',
        ],
        'CasAppEnv' => [
            'Type' => 'string',
            'Length' => 20,
            'Required' => true,
            'Default' => 'local',
            'LongLabel' => 'Ambiente da aplicação',
            'ShortLabel' => 'Ambiente',
            'TextPlaceholder' => '',
            'TextHelp' => '(local, development, staging, production)',
        ],
        'CasAppUrl' => [
            'Type' => 'string',
            'Length' => 2000,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'URL do App',
            'ShortLabel' => 'URL do App',
            'TextPlaceholder' => 'http://localhost:8080',
            'TextHelp' => 'URL base da sua aplicação',
        ],
        'CasAppAdmFirstName' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Primeiro Nome',
            'ShortLabel' => 'Primeiro Nome',
            'TextPlaceholder' => 'Seu primeiro nome',
            'TextHelp' => '',
        ],
        'CasAppAdmLastName' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Sobrenome',
            'ShortLabel' => 'Sobrenome',
            'TextPlaceholder' => 'Seu último nome',
            'TextHelp' => '',
        ],
        'CasAppAdmAccount' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Conta de acesso',
            'ShortLabel' => 'Conta de acesso',
            'TextPlaceholder' => 'email@provedor.com',
            'TextHelp' => 'Utilize um e-mail válido.',
        ],
        'CasAppAdmPassword' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Senha',
            'ShortLabel' => 'Senha',
            'TextPlaceholder' => '',
            'TextHelp' => 'Utilize letras, números e caracteres especiais.',
        ],
        'CasAppAdmProfile' => [
            'Type' => 'string',
            'Length' => 20,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Perfil de Acesso',
            'ShortLabel' => 'Perfil de Acesso',
            'TextPlaceholder' => '',
            'TextHelp' => 'Perfil de acesso ao sistema (ADMINISTRATOR, SUPPORT, USER)',
        ],
        'CasAppSupFirstName' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Primeiro Nome',
            'ShortLabel' => 'Primeiro Nome',
            'TextPlaceholder' => 'Seu primeiro nome',
            'TextHelp' => '',
        ],
        'CasAppSupLastName' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Sobrenome',
            'ShortLabel' => 'Sobrenome',
            'TextPlaceholder' => 'Seu último nome',
            'TextHelp' => '',
        ],
        'CasAppSupAccount' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Conta de acesso',
            'ShortLabel' => 'Conta de acesso',
            'TextPlaceholder' => 'email@provedor.com',
            'TextHelp' => 'Utilize um e-mail válido.',
        ],
        'CasAppSupPassword' => [
            'Type' => 'string',
            'Length' => 255,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Senha',
            'ShortLabel' => 'Senha',
            'TextPlaceholder' => '',
            'TextHelp' => 'Utilize letras números e caracteres especiais.',
        ],
        'CasAppSupProfile' => [
            'Type' => 'string',
            'Length' => 20,
            'Required' => true,
            'Default' => null,
            'LongLabel' => 'Perfil de Acesso',
            'ShortLabel' => 'Perfil de Acesso',
            'TextPlaceholder' => '',
            'TextHelp' => 'Perfil de acesso ao sistema (ADMINISTRATOR, SUPPORT, USER)',
        ],
    ];
    // Foreign //
    public const FIELDS_FOREIGN = [];
    public const FIELDS_MD_FOREIGN = [];
}
